services:
  edusms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edusms
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "3000:3000"
    networks:
      - dokploy-network
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      FORCE_HTTPS: ${FORCE_HTTPS}

      LOG_CHANNEL: ${LOG_CHANNEL}

      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  dokploy-network:
    external: true
