
services:
  schoolify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolify_host
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - schoolify_data:/app/public/uploads
    networks:
      - dokploy-network

volumes:
  schoolify_data:

networks:
  dokploy-network:
    external: true
