
services:
  schoolify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolify_host
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ${HOME}/edusms/uploads:/app/public/uploads
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
