
services:
  schoolify:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schoolify_host
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - uploads:/app/public/uploads
      - storage:/app/storage
    networks:
      - dokploy-network

volumes:
  uploads:
  storage:

networks:
  dokploy-network:
    external: true
