services:
  postgres:
    image: mariadb:latest
    container_name: schoolifydb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    restart: unless-stopped
    ports:
      - "3000:3000"

  adminer:
    depends_on:
      - postgres
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"

  php-dev:
    image: "webdevops/php-nginx-dev:8.2-alpine"
    working_dir: /var/www
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/default.conf:/opt/docker/etc/nginx/vhost.conf
